2021-12-01 11:00:16,888 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-01 11:00:16,896 User authentication hooks NOT provided (default user enabled)
2021-12-01 11:00:16,904 Bokeh app running at: http://localhost:80/etc-prototype
2021-12-01 11:00:16,904 Starting Bokeh server with process id: 4768
2021-12-01 11:02:55,537 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-01 11:02:55,537 User authentication hooks NOT provided (default user enabled)
2021-12-01 11:02:55,545 Bokeh app running at: http://localhost:80/etc-prototype
2021-12-01 11:02:55,545 Starting Bokeh server with process id: 25868
2021-12-01 11:03:05,249 WebSocket connection opened
2021-12-01 11:03:05,249 ServerConnection created
2021-12-01 11:25:33,201 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-01 11:25:33,213 User authentication hooks NOT provided (default user enabled)
2021-12-01 11:25:33,227 Bokeh app running at: http://localhost:80/etc-prototype
2021-12-01 11:25:33,227 Starting Bokeh server with process id: 20052
2021-12-01 11:26:40,149 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-01 11:26:40,151 User authentication hooks NOT provided (default user enabled)
2021-12-01 11:26:40,157 Bokeh app running at: http://localhost:80/etc-prototype
2021-12-01 11:26:40,157 Starting Bokeh server with process id: 25828
2021-12-01 11:27:15,396 Error running application handler <bokeh.application.handlers.directory.DirectoryHandler object at 0x000001E2FED98610>: [Errno 2] No such file or directory: 'static/mouseover_text.yaml'
File "main.py", line 774, in <module>:
page_loaded_callback = CustomJS(args={'titles':yaml.safe_load(open('static/mouseover_text.yaml'))}, code=page_loaded_js) Traceback (most recent call last):
  File "c:\users\12069\appdata\local\programs\python\python38\lib\site-packages\bokeh\application\handlers\code_runner.py", line 197, in run
    exec(self._code, module.__dict__)
  File "C:\Users\12069\Documents\WMKO_Documents\etc-prototype\main.py", line 774, in <module>
    page_loaded_callback = CustomJS(args={'titles':yaml.safe_load(open('static/mouseover_text.yaml'))}, code=page_loaded_js)
FileNotFoundError: [Errno 2] No such file or directory: 'static/mouseover_text.yaml'
 
2021-12-01 11:27:15,406 Uncaught exception GET /etc-prototype (::1)
HTTPServerRequest(protocol='http', host='localhost', method='GET', uri='/etc-prototype', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "c:\users\12069\appdata\local\programs\python\python38\lib\site-packages\tornado\web.py", line 1704, in _execute
    result = await result
  File "c:\users\12069\appdata\local\programs\python\python38\lib\site-packages\bokeh\server\views\doc_handler.py", line 54, in get
    page = server_html_page_for_session(session,
  File "c:\users\12069\appdata\local\programs\python\python38\lib\site-packages\bokeh\embed\server.py", line 238, in server_html_page_for_session
    html = html_page_for_render_items(bundle, {}, [render_item], title,
  File "c:\users\12069\appdata\local\programs\python\python38\lib\site-packages\bokeh\embed\elements.py", line 126, in html_page_for_render_items
    html = template.render(context)
  File "c:\users\12069\appdata\local\programs\python\python38\lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "c:\users\12069\appdata\local\programs\python\python38\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\12069\Documents\WMKO_Documents\etc-prototype\templates\index.html", line 1, in top-level template code
    {% extends base %}
  File "c:\users\12069\appdata\local\programs\python\python38\lib\site-packages\bokeh\core\_templates\file.html", line 40, in top-level template code
    {% block body %}
  File "c:\users\12069\appdata\local\programs\python\python38\lib\site-packages\bokeh\core\_templates\file.html", line 42, in block 'body'
    {% block inner_body %}
  File "c:\users\12069\appdata\local\programs\python\python38\lib\site-packages\bokeh\core\_templates\file.html", line 43, in block 'inner_body'
    {% block contents %}
  File "C:\Users\12069\Documents\WMKO_Documents\etc-prototype\templates\index.html", line 40, in block 'contents'
    {{ embed(roots.reset_button) }}
  File "c:\users\12069\appdata\local\programs\python\python38\lib\site-packages\jinja2\environment.py", line 474, in getattr
    return getattr(obj, attribute)
  File "c:\users\12069\appdata\local\programs\python\python38\lib\site-packages\bokeh\embed\util.py", line 244, in __getattr__
    return self.__getitem__(key)
  File "c:\users\12069\appdata\local\programs\python\python38\lib\site-packages\bokeh\embed\util.py", line 239, in __getitem__
    raise ValueError("root with '%s' name not found" % key)
ValueError: root with 'reset_button' name not found
2021-12-01 11:27:15,484 500 GET /etc-prototype (::1) 928.47ms
2021-12-01 11:27:15,872 404 GET /favicon.ico (::1) 1.00ms
2021-12-01 11:36:46,026 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-01 11:36:46,028 User authentication hooks NOT provided (default user enabled)
2021-12-01 11:36:46,032 Bokeh app running at: http://localhost:80/etc-prototype
2021-12-01 11:36:46,032 Starting Bokeh server with process id: 4676
2021-12-01 11:36:53,626 WebSocket connection opened
2021-12-01 11:36:53,627 ServerConnection created
2021-12-01 11:37:27,838 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-01 11:37:27,840 User authentication hooks NOT provided (default user enabled)
2021-12-01 11:37:27,845 Bokeh app running at: http://localhost:80/etc-prototype
2021-12-01 11:37:27,845 Starting Bokeh server with process id: 14440
2021-12-01 11:37:32,563 WebSocket connection opened
2021-12-01 11:37:32,563 ServerConnection created
2021-12-01 11:39:37,158 WebSocket connection closed: code=1001, reason=None
2021-12-01 11:43:53,034 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-01 11:43:53,036 User authentication hooks NOT provided (default user enabled)
2021-12-01 11:43:53,041 Bokeh app running at: http://localhost:5006/etc-prototype
2021-12-01 11:43:53,041 Starting Bokeh server with process id: 4872
2021-12-01 11:45:56,799 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-01 11:45:56,802 User authentication hooks NOT provided (default user enabled)
2021-12-01 11:45:56,805 Bokeh app running at: http://localhost:10/etc-prototype
2021-12-01 11:45:56,805 Starting Bokeh server with process id: 1784
2021-12-01 11:46:34,864 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-01 11:46:34,866 User authentication hooks NOT provided (default user enabled)
2021-12-01 11:46:34,870 Bokeh app running at: http://localhost:5006/etc-prototype
2021-12-01 11:46:34,870 Starting Bokeh server with process id: 16336
2021-12-01 11:48:24,953 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-01 11:48:24,956 User authentication hooks NOT provided (default user enabled)
2021-12-01 11:48:24,959 Bokeh app running at: http://localhost:5006/etc-prototype
2021-12-01 11:48:24,959 Starting Bokeh server with process id: 17348
2021-12-01 11:55:07,338 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-01 11:55:07,339 Cannot start Bokeh server, port 5006 is already in use
2021-12-01 11:59:44,556 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-01 11:59:44,557 Cannot start Bokeh server, port 5006 is already in use
2021-12-01 12:16:33,068 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-01 12:16:33,068 Cannot start Bokeh server, port 5006 is already in use
2021-12-01 12:16:53,919 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-01 12:16:53,921 User authentication hooks NOT provided (default user enabled)
2021-12-01 12:16:53,928 Bokeh app running at: http://localhost:80/etc-prototype
2021-12-01 12:16:53,928 Starting Bokeh server with process id: 12148
2021-12-01 12:18:11,997 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-01 12:18:11,998 Cannot start Bokeh server, port 5006 is already in use
2021-12-02 10:03:12,287 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-02 10:03:12,288 User authentication hooks NOT provided (default user enabled)
2021-12-02 10:03:12,293 Bokeh app running at: http://localhost:8080/prototype
2021-12-02 10:03:12,294 Starting Bokeh server with process id: 26457
2021-12-02 10:31:16,981 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-02 10:31:16,982 Cannot start Bokeh server [EACCES]: PermissionError(13, 'Permission denied')
2021-12-02 10:31:34,040 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-02 10:31:34,042 User authentication hooks NOT provided (default user enabled)
2021-12-02 10:31:34,045 Bokeh app running at: http://localhost:8000/prototype
2021-12-02 10:31:34,045 Starting Bokeh server with process id: 28077
2021-12-02 10:40:28,907 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-02 10:40:28,908 User authentication hooks NOT provided (default user enabled)
2021-12-02 10:40:28,914 Bokeh app running at: http://localhost:8080/prototype
2021-12-02 10:40:28,914 Starting Bokeh server with process id: 29000
2021-12-02 10:43:47,447 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-02 10:43:47,449 User authentication hooks NOT provided (default user enabled)
2021-12-02 10:43:47,453 Bokeh app running at: http://localhost:5000/prototype
2021-12-02 10:43:47,453 Starting Bokeh server with process id: 29212
2021-12-02 11:45:17,355 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-02 11:45:17,356 User authentication hooks NOT provided (default user enabled)
2021-12-02 11:45:17,361 Bokeh app running at: http://localhost:8000/prototype
2021-12-02 11:45:17,362 Starting Bokeh server with process id: 30461
2021-12-02 12:30:26,627 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-02 12:30:26,629 User authentication hooks NOT provided (default user enabled)
2021-12-02 12:30:26,635 Bokeh app running at: http://localhost:8000/prototype
2021-12-02 12:30:26,635 Starting Bokeh server with process id: 31787
2021-12-02 12:30:41,769 Error running application handler <bokeh.application.handlers.directory.DirectoryHandler object at 0x7fb379b39cd0>: No module named 'Instrument'
File "ETC.py", line 2, in <module>:
from Instrument import instrument Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/application/handlers/code_runner.py", line 197, in run
    exec(self._code, module.__dict__)
  File "/usr/local/home/kblair/Documents/ETC/prototype/main.py", line 10, in <module>
    from calculator.ETC import exposure_time_calculator
  File "/usr/local/home/kblair/Documents/ETC/prototype/calculator/ETC.py", line 2, in <module>
    from Instrument import instrument
ModuleNotFoundError: No module named 'Instrument'
 
2021-12-02 12:30:41,782 Uncaught exception GET /prototype (10.198.0.90)
HTTPServerRequest(protocol='http', host='vm-internship:8000', method='GET', uri='/prototype', version='HTTP/1.1', remote_ip='10.198.0.90')
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/server/views/doc_handler.py", line 54, in get
    page = server_html_page_for_session(session,
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/embed/server.py", line 238, in server_html_page_for_session
    html = html_page_for_render_items(bundle, {}, [render_item], title,
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/embed/elements.py", line 126, in html_page_for_render_items
    html = template.render(context)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/anaconda3/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/anaconda3/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/home/kblair/Documents/ETC/prototype/templates/index.html", line 1, in top-level template code
    {% extends base %}
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/core/_templates/file.html", line 40, in top-level template code
    {% block body %}
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/core/_templates/file.html", line 42, in block "body"
    {% block inner_body %}
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/core/_templates/file.html", line 43, in block "inner_body"
    {% block contents %}
  File "/usr/local/home/kblair/Documents/ETC/prototype/templates/index.html", line 40, in block "contents"
    {{ embed(roots.reset_button) }}
  File "/usr/local/anaconda3/lib/python3.8/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/embed/util.py", line 244, in __getattr__
    return self.__getitem__(key)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/embed/util.py", line 239, in __getitem__
    raise ValueError("root with '%s' name not found" % key)
ValueError: root with 'reset_button' name not found
2021-12-02 12:30:41,785 500 GET /prototype (10.198.0.90) 438.52ms
2021-12-02 12:30:41,854 404 GET /favicon.ico (10.198.0.90) 0.91ms
2021-12-02 13:28:51,864 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-02 13:28:51,866 User authentication hooks NOT provided (default user enabled)
2021-12-02 13:28:51,870 Bokeh app running at: http://localhost:8080/prototype
2021-12-02 13:28:51,870 Starting Bokeh server with process id: 1471
2021-12-02 13:28:54,883 Refusing websocket connection from Origin 'http://vm-internship:8080';                       use --allow-websocket-origin=vm-internship:8080 or set BOKEH_ALLOW_WS_ORIGIN=vm-internship:8080 to permit this; currently we allow origins {'localhost:8080'}
2021-12-02 13:28:54,883 403 GET /prototype/ws (10.198.0.90) 0.91ms
2021-12-02 13:31:35,966 Refusing websocket connection from Origin 'http://10.96.10.12:8080';                       use --allow-websocket-origin=10.96.10.12:8080 or set BOKEH_ALLOW_WS_ORIGIN=10.96.10.12:8080 to permit this; currently we allow origins {'localhost:8080'}
2021-12-02 13:31:35,966 403 GET /prototype/ws (10.198.0.90) 0.97ms
2021-12-02 13:31:45,573 Refusing websocket connection from Origin 'http://10.96.10.12:8080';                       use --allow-websocket-origin=10.96.10.12:8080 or set BOKEH_ALLOW_WS_ORIGIN=10.96.10.12:8080 to permit this; currently we allow origins {'localhost:8080'}
2021-12-02 13:31:45,573 403 GET /prototype/ws (10.198.0.90) 0.74ms
2021-12-02 13:34:31,539 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-02 13:34:31,540 User authentication hooks NOT provided (default user enabled)
2021-12-02 13:34:31,543 Bokeh app running at: http://localhost:8080/prototype
2021-12-02 13:34:31,544 Starting Bokeh server with process id: 1873
2021-12-02 13:34:35,659 Refusing websocket connection from Origin 'http://10.96.10.12:8080';                       use --allow-websocket-origin=10.96.10.12:8080 or set BOKEH_ALLOW_WS_ORIGIN=10.96.10.12:8080 to permit this; currently we allow origins {'10.96.10.12 :8080'}
2021-12-02 13:34:35,660 403 GET /prototype/ws (10.198.0.90) 0.88ms
2021-12-02 13:35:19,833 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-02 13:35:19,834 Cannot start Bokeh server, port 8080 is already in use
2021-12-02 13:45:32,521 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-02 13:45:32,522 Cannot start Bokeh server, port 8080 is already in use
2021-12-02 13:45:35,206 Refusing websocket connection from Origin 'http://10.96.10.12:8080';                       use --allow-websocket-origin=10.96.10.12:8080 or set BOKEH_ALLOW_WS_ORIGIN=10.96.10.12:8080 to permit this; currently we allow origins {'10.96.10.12 :8080'}
2021-12-02 13:45:35,206 403 GET /prototype/ws (10.198.0.90) 0.87ms
2021-12-02 13:45:39,181 Refusing websocket connection from Origin 'http://10.96.10.12:8080';                       use --allow-websocket-origin=10.96.10.12:8080 or set BOKEH_ALLOW_WS_ORIGIN=10.96.10.12:8080 to permit this; currently we allow origins {'10.96.10.12 :8080'}
2021-12-02 13:45:39,182 403 GET /prototype/ws (10.198.0.90) 0.71ms
2021-12-02 13:46:08,582 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-02 13:46:08,583 Cannot start Bokeh server, port 8080 is already in use
2021-12-02 13:48:29,760 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-02 13:48:29,761 User authentication hooks NOT provided (default user enabled)
2021-12-02 13:48:29,765 Bokeh app running at: http://localhost:8080/prototype
2021-12-02 13:48:29,765 Starting Bokeh server with process id: 2713
2021-12-02 13:49:19,929 WebSocket connection opened
2021-12-02 13:49:19,930 ServerConnection created
2021-12-02 13:49:35,018 WebSocket connection closed: code=1001, reason=None
2021-12-02 13:49:35,174 Refusing websocket connection from Origin 'http://vm-internship:8080';                       use --allow-websocket-origin=vm-internship:8080 or set BOKEH_ALLOW_WS_ORIGIN=vm-internship:8080 to permit this; currently we allow origins {'10.96.10.12:8080'}
2021-12-02 13:49:35,175 403 GET /prototype/ws (10.198.0.90) 0.97ms
2021-12-02 13:50:13,216 WebSocket connection opened
2021-12-02 13:50:13,257 ServerConnection created
2021-12-02 14:01:59,657 WebSocket connection closed: code=1001, reason=None
2021-12-02 14:02:46,903 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-02 14:02:46,905 User authentication hooks NOT provided (default user enabled)
2021-12-02 14:02:46,910 Bokeh app running at: http://localhost:8000/prototype
2021-12-02 14:02:46,910 Starting Bokeh server with process id: 4079
2021-12-02 14:02:49,802 WebSocket connection opened
2021-12-02 14:02:49,802 ServerConnection created
2021-12-02 14:03:11,692 WebSocket connection closed: code=1001, reason=None
2021-12-02 14:03:11,829 WebSocket connection opened
2021-12-02 14:03:11,829 ServerConnection created
2021-12-02 14:09:05,586 WebSocket connection closed: code=1001, reason=None
2021-12-02 14:09:05,787 WebSocket connection opened
2021-12-02 14:09:05,788 ServerConnection created
2021-12-02 16:45:01,057 Error running application handler <bokeh.application.handlers.directory.DirectoryHandler object at 0x7f50c094adf0>: [Errno 2] No such file or directory: 'static/etc_instructions.txt'
File "main.py", line 424, in __init__:
with open('static/gui_instructions.txt') as file: Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/application/handlers/code_runner.py", line 197, in run
    exec(self._code, module.__dict__)
  File "/usr/local/home/kblair/Documents/ETC/prototype/main.py", line 823, in <module>
    help = instruction_text()
  File "/usr/local/home/kblair/Documents/ETC/prototype/main.py", line 424, in __init__
    with open('static/gui_instructions.txt') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'static/etc_instructions.txt'
 
2021-12-02 16:45:01,065 Uncaught exception GET /prototype (10.198.0.90)
HTTPServerRequest(protocol='http', host='vm-internship:8000', method='GET', uri='/prototype', version='HTTP/1.1', remote_ip='10.198.0.90')
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/server/views/doc_handler.py", line 54, in get
    page = server_html_page_for_session(session,
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/embed/server.py", line 238, in server_html_page_for_session
    html = html_page_for_render_items(bundle, {}, [render_item], title,
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/embed/elements.py", line 126, in html_page_for_render_items
    html = template.render(context)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/anaconda3/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/anaconda3/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/home/kblair/Documents/ETC/prototype/templates/index.html", line 1, in top-level template code
    {% extends base %}
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/core/_templates/file.html", line 40, in top-level template code
    {% block body %}
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/core/_templates/file.html", line 42, in block "body"
    {% block inner_body %}
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/core/_templates/file.html", line 43, in block "inner_body"
    {% block contents %}
  File "/usr/local/home/kblair/Documents/ETC/prototype/templates/index.html", line 43, in block "contents"
    {{ embed(roots.instruments) }}
  File "/usr/local/anaconda3/lib/python3.8/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/embed/util.py", line 244, in __getattr__
    return self.__getitem__(key)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/embed/util.py", line 239, in __getitem__
    raise ValueError("root with '%s' name not found" % key)
ValueError: root with 'instruments' name not found
2021-12-02 16:45:01,068 500 GET /prototype (10.198.0.90) 26.92ms
2021-12-02 16:45:05,630 Error running application handler <bokeh.application.handlers.directory.DirectoryHandler object at 0x7f50c094adf0>: [Errno 2] No such file or directory: 'static/etc_instructions.txt'
File "main.py", line 424, in __init__:
with open('static/gui_instructions.txt') as file: Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/application/handlers/code_runner.py", line 197, in run
    exec(self._code, module.__dict__)
  File "/usr/local/home/kblair/Documents/ETC/prototype/main.py", line 823, in <module>
    help = instruction_text()
  File "/usr/local/home/kblair/Documents/ETC/prototype/main.py", line 424, in __init__
    with open('static/gui_instructions.txt') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'static/etc_instructions.txt'
 
2021-12-02 16:45:05,635 Uncaught exception GET /prototype (10.198.0.90)
HTTPServerRequest(protocol='http', host='vm-internship:8000', method='GET', uri='/prototype', version='HTTP/1.1', remote_ip='10.198.0.90')
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/server/views/doc_handler.py", line 54, in get
    page = server_html_page_for_session(session,
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/embed/server.py", line 238, in server_html_page_for_session
    html = html_page_for_render_items(bundle, {}, [render_item], title,
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/embed/elements.py", line 126, in html_page_for_render_items
    html = template.render(context)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/anaconda3/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/anaconda3/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/home/kblair/Documents/ETC/prototype/templates/index.html", line 1, in top-level template code
    {% extends base %}
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/core/_templates/file.html", line 40, in top-level template code
    {% block body %}
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/core/_templates/file.html", line 42, in block "body"
    {% block inner_body %}
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/core/_templates/file.html", line 43, in block "inner_body"
    {% block contents %}
  File "/usr/local/home/kblair/Documents/ETC/prototype/templates/index.html", line 43, in block "contents"
    {{ embed(roots.instruments) }}
  File "/usr/local/anaconda3/lib/python3.8/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/embed/util.py", line 244, in __getattr__
    return self.__getitem__(key)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/embed/util.py", line 239, in __getitem__
    raise ValueError("root with '%s' name not found" % key)
ValueError: root with 'instruments' name not found
2021-12-02 16:45:05,635 500 GET /prototype (10.198.0.90) 20.12ms
2021-12-02 16:45:26,529 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-02 16:45:26,531 User authentication hooks NOT provided (default user enabled)
2021-12-02 16:45:26,534 Bokeh app running at: http://localhost:8000/prototype
2021-12-02 16:45:26,534 Starting Bokeh server with process id: 10785
2021-12-02 16:45:30,380 Refusing websocket connection from Origin 'http://vm-internship:8000';                       use --allow-websocket-origin=vm-internship:8000 or set BOKEH_ALLOW_WS_ORIGIN=vm-internship:8000 to permit this; currently we allow origins {'10.96.10.12:8000'}
2021-12-02 16:45:30,380 403 GET /prototype/ws (10.198.0.90) 0.78ms
2021-12-02 16:46:55,438 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-02 16:46:55,439 User authentication hooks NOT provided (default user enabled)
2021-12-02 16:46:55,444 Bokeh app running at: http://localhost:8000/prototype
2021-12-02 16:46:55,444 Starting Bokeh server with process id: 11026
2021-12-02 16:46:58,607 Refusing websocket connection from Origin 'http://vm-internship:8000';                       use --allow-websocket-origin=vm-internship:8000 or set BOKEH_ALLOW_WS_ORIGIN=vm-internship:8000 to permit this; currently we allow origins {'10.96.10.12:8000'}
2021-12-02 16:46:58,607 403 GET /prototype/ws (10.198.0.90) 0.87ms
2021-12-02 16:48:09,890 WebSocket connection opened
2021-12-02 16:48:09,891 ServerConnection created
2021-12-03 08:41:03,933 WebSocket connection closed: code=1001, reason=None
2021-12-03 08:41:04,228 WebSocket connection opened
2021-12-03 08:41:04,229 ServerConnection created
2021-12-03 09:45:52,744 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-03 09:45:52,746 User authentication hooks NOT provided (default user enabled)
2021-12-03 09:45:52,752 Bokeh app running at: http://localhost:8000/prototype
2021-12-03 09:45:52,752 Starting Bokeh server with process id: 28623
2021-12-03 09:45:55,824 WebSocket connection opened
2021-12-03 09:45:55,825 ServerConnection created
2021-12-03 09:45:56,659 error handling message
 message: Message 'PATCH-DOC' content: {'events': [{'kind': 'MessageSent', 'msg_type': 'bokeh_event', 'msg_data': {'event_name': 'document_ready', 'event_values': {}}}], 'references': []} 
 error: AttributeError("'source' object has no attribute '_define_vegamag'")
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/server/protocol_handler.py", line 90, in handle
    work = await handler(message, connection)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/server/session.py", line 67, in _needs_document_lock_wrapper
    result = func(self, *args, **kwargs)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/server/session.py", line 261, in _handle_patch
    message.apply_to_document(self.document, self)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/protocol/messages/patch_doc.py", line 100, in apply_to_document
    doc._with_self_as_curdoc(lambda: doc.apply_json_patch(self.content, setter))
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/document/document.py", line 1198, in _with_self_as_curdoc
    return f()
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/protocol/messages/patch_doc.py", line 100, in <lambda>
    doc._with_self_as_curdoc(lambda: doc.apply_json_patch(self.content, setter))
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/document/document.py", line 398, in apply_json_patch
    self._trigger_on_message(event_json["msg_type"], event_json["msg_data"])
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/document/document.py", line 687, in _trigger_on_message
    cb(msg_data)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/document/document.py", line 359, in apply_json_event
    cb(event)
  File "/usr/local/home/kblair/Documents/ETC/prototype/main.py", line 837, in load_contents
    etc = exposure_time_calculator()
  File "/usr/local/home/kblair/Documents/ETC/prototype/calculator/ETC.py", line 146, in __init__
    self.source = source()
  File "/usr/local/home/kblair/Documents/ETC/prototype/calculator/Source.py", line 192, in __init__
    self._define_vegamag()
AttributeError: 'source' object has no attribute '_define_vegamag'
2021-12-03 09:46:34,330 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-03 09:46:34,332 User authentication hooks NOT provided (default user enabled)
2021-12-03 09:46:34,337 Bokeh app running at: http://localhost:8000/prototype
2021-12-03 09:46:34,337 Starting Bokeh server with process id: 28703
2021-12-03 09:46:36,286 WebSocket connection opened
2021-12-03 09:46:36,287 ServerConnection created
2021-12-03 09:51:00,007 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-03 09:51:00,010 User authentication hooks NOT provided (default user enabled)
2021-12-03 09:51:00,019 Bokeh app running at: http://localhost:8000/prototype
2021-12-03 09:51:00,019 Starting Bokeh server with process id: 28887
2021-12-03 09:51:02,914 WebSocket connection opened
2021-12-03 09:51:02,915 ServerConnection created
2021-12-03 09:52:43,943 error handling message
 message: Message 'PATCH-DOC' content: {'events': [{'kind': 'ModelChanged', 'model': {'id': '1604'}, 'attr': 'value', 'new': 'deg_C'}], 'references': []} 
 error: ValueError("failed to validate Spinner(id='1602', ...).step: expected a value of type Float in range [1e-16, inf], got -272.15")
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/server/protocol_handler.py", line 90, in handle
    work = await handler(message, connection)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/server/session.py", line 67, in _needs_document_lock_wrapper
    result = func(self, *args, **kwargs)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/server/session.py", line 261, in _handle_patch
    message.apply_to_document(self.document, self)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/protocol/messages/patch_doc.py", line 100, in apply_to_document
    doc._with_self_as_curdoc(lambda: doc.apply_json_patch(self.content, setter))
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/document/document.py", line 1198, in _with_self_as_curdoc
    return f()
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/protocol/messages/patch_doc.py", line 100, in <lambda>
    doc._with_self_as_curdoc(lambda: doc.apply_json_patch(self.content, setter))
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/document/document.py", line 411, in apply_json_patch
    patched_obj.set_from_json(attr, value, models=references, setter=setter)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/core/has_props.py", line 412, in set_from_json
    descriptor.set_from_json(self, json, models, setter)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/core/property/descriptors.py", line 623, in set_from_json
    return super().set_from_json(obj, self.property.from_json(json, models), models, setter)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/core/property/descriptors.py", line 327, in set_from_json
    self._internal_set(obj, json, setter=setter)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/core/property/descriptors.py", line 786, in _internal_set
    self._real_set(obj, old, value, hint=hint, setter=setter)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/core/property/descriptors.py", line 849, in _real_set
    self._trigger(obj, old, value, hint=hint, setter=setter)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/core/property/descriptors.py", line 926, in _trigger
    obj.trigger(self.name, old, value, hint, setter)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/model.py", line 682, in trigger
    super().trigger(descriptor.name, old, new, hint=hint, setter=setter)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/util/callback_manager.py", line 163, in trigger
    self._document._notify_change(self, attr, old, new, hint, setter, invoke)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/document/document.py", line 1090, in _notify_change
    self._trigger_on_change(event)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/document/document.py", line 1180, in _trigger_on_change
    self._with_self_as_curdoc(event.callback_invoker)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/document/document.py", line 1198, in _with_self_as_curdoc
    return f()
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/util/callback_manager.py", line 161, in invoke
    callback(attr, old, new)
  File "/usr/local/home/kblair/Documents/ETC/prototype/main.py", line 94, in unit_callback
    self.contents.children[0].step = (self.contents.children[0].step * unit_old).to(unit_mid).to(unit_new, equivalencies=self.equivalency).value
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/core/has_props.py", line 298, in __setattr__
    super().__setattr__(name, value)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/core/property/descriptors.py", line 552, in __set__
    self._internal_set(obj, value, setter=setter)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/core/property/descriptors.py", line 784, in _internal_set
    value = self.property.prepare_value(obj, self.name, value)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/core/property/bases.py", line 350, in prepare_value
    raise ValueError(f"failed to validate {obj_repr}.{name}: {error}")
ValueError: failed to validate Spinner(id='1602', ...).step: expected a value of type Float in range [1e-16, inf], got -272.15
2021-12-03 11:00:13,878 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-03 11:00:13,879 User authentication hooks NOT provided (default user enabled)
2021-12-03 11:00:13,883 Bokeh app running at: http://localhost:8000/prototype
2021-12-03 11:00:13,883 Starting Bokeh server with process id: 30263
2021-12-03 11:00:15,815 WebSocket connection opened
2021-12-03 11:00:15,815 ServerConnection created
2021-12-03 11:04:12,898 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-03 11:04:12,899 User authentication hooks NOT provided (default user enabled)
2021-12-03 11:04:12,903 Bokeh app running at: http://localhost:8000/prototype
2021-12-03 11:04:12,903 Starting Bokeh server with process id: 30460
2021-12-03 11:04:15,070 WebSocket connection opened
2021-12-03 11:04:15,070 ServerConnection created
2021-12-03 11:05:04,668 WebSocket connection closed: code=1001, reason=None
2021-12-03 11:05:04,787 WebSocket connection opened
2021-12-03 11:05:04,788 ServerConnection created
2021-12-03 11:06:02,370 WebSocket connection closed: code=1001, reason=None
2021-12-03 11:06:02,469 WebSocket connection opened
2021-12-03 11:06:02,469 ServerConnection created
2021-12-03 11:07:17,315 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-03 11:07:17,317 User authentication hooks NOT provided (default user enabled)
2021-12-03 11:07:17,321 Bokeh app running at: http://localhost:8000/prototype
2021-12-03 11:07:17,321 Starting Bokeh server with process id: 30596
2021-12-03 11:07:19,787 WebSocket connection opened
2021-12-03 11:07:19,788 ServerConnection created
2021-12-03 15:12:14,642 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-03 15:12:14,644 User authentication hooks NOT provided (default user enabled)
2021-12-03 15:12:14,650 Bokeh app running at: http://localhost:8000/prototype
2021-12-03 15:12:14,650 Starting Bokeh server with process id: 2432
2021-12-03 15:12:18,721 WebSocket connection opened
2021-12-03 15:12:18,722 ServerConnection created
2021-12-03 15:13:12,967 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-03 15:13:12,970 User authentication hooks NOT provided (default user enabled)
2021-12-03 15:13:12,978 Bokeh app running at: http://localhost:8000/prototype
2021-12-03 15:13:12,978 Starting Bokeh server with process id: 2516
2021-12-03 15:13:15,564 WebSocket connection opened
2021-12-03 15:13:15,565 ServerConnection created
2021-12-03 15:16:07,754 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-03 15:16:07,756 User authentication hooks NOT provided (default user enabled)
2021-12-03 15:16:07,761 Bokeh app running at: http://localhost:8000/prototype
2021-12-03 15:16:07,761 Starting Bokeh server with process id: 2626
2021-12-03 15:16:09,799 WebSocket connection opened
2021-12-03 15:16:09,799 ServerConnection created
2021-12-03 15:16:12,320 error handling message
 message: Message 'PATCH-DOC' content: {'events': [{'kind': 'MessageSent', 'msg_type': 'bokeh_event', 'msg_data': {'event_name': 'document_ready', 'event_values': {}}}], 'references': []} 
 error: TypeError('create_data() takes 2 positional arguments but 4 were given')
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/server/protocol_handler.py", line 90, in handle
    work = await handler(message, connection)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/server/session.py", line 67, in _needs_document_lock_wrapper
    result = func(self, *args, **kwargs)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/server/session.py", line 261, in _handle_patch
    message.apply_to_document(self.document, self)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/protocol/messages/patch_doc.py", line 100, in apply_to_document
    doc._with_self_as_curdoc(lambda: doc.apply_json_patch(self.content, setter))
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/document/document.py", line 1198, in _with_self_as_curdoc
    return f()
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/protocol/messages/patch_doc.py", line 100, in <lambda>
    doc._with_self_as_curdoc(lambda: doc.apply_json_patch(self.content, setter))
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/document/document.py", line 398, in apply_json_patch
    self._trigger_on_message(event_json["msg_type"], event_json["msg_data"])
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/document/document.py", line 687, in _trigger_on_message
    cb(msg_data)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/document/document.py", line 359, in apply_json_event
    cb(event)
  File "/usr/local/home/kblair/Documents/ETC/prototype/main.py", line 859, in load_contents
    res.load()
  File "/usr/local/home/kblair/Documents/ETC/prototype/main.py", line 671, in load
    self.create_data('none', self.wavelength.location, self.wavelength.location)
TypeError: create_data() takes 2 positional arguments but 4 were given
2021-12-06 09:25:32,844 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-06 09:29:31,264 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-06 13:59:25,409 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-06 13:59:25,410 User authentication hooks NOT provided (default user enabled)
2021-12-06 13:59:25,414 Bokeh app running at: http://localhost:8000/prototype
2021-12-06 13:59:25,414 Starting Bokeh server with process id: 5420
2021-12-06 13:59:29,039 WebSocket connection opened
2021-12-06 13:59:29,039 ServerConnection created
2021-12-06 13:59:32,901 WebSocket connection closed: code=1001, reason=None
2021-12-06 13:59:33,081 WebSocket connection opened
2021-12-06 13:59:33,082 ServerConnection created
2021-12-06 14:00:29,122 WebSocket connection closed: code=1001, reason=None
2021-12-06 14:00:29,285 WebSocket connection opened
2021-12-06 14:00:29,285 ServerConnection created
2021-12-06 14:00:33,738 WebSocket connection closed: code=1001, reason=None
2021-12-06 14:00:33,878 WebSocket connection opened
2021-12-06 14:00:33,879 ServerConnection created
2021-12-06 14:01:06,163 WebSocket connection closed: code=1001, reason=None
2021-12-06 14:01:06,335 WebSocket connection opened
2021-12-06 14:01:06,336 ServerConnection created
2021-12-06 14:01:20,038 WebSocket connection closed: code=1001, reason=None
2021-12-06 14:01:20,188 WebSocket connection opened
2021-12-06 14:01:20,189 ServerConnection created
2021-12-06 14:01:45,528 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-06 14:01:45,530 User authentication hooks NOT provided (default user enabled)
2021-12-06 14:01:45,534 Bokeh app running at: http://localhost:8000/prototype
2021-12-06 14:01:45,534 Starting Bokeh server with process id: 5612
2021-12-06 14:01:47,898 WebSocket connection opened
2021-12-06 14:01:47,898 ServerConnection created
2021-12-06 14:03:33,586 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-06 14:03:33,587 User authentication hooks NOT provided (default user enabled)
2021-12-06 14:03:33,591 Bokeh app running at: http://localhost:8000/prototype
2021-12-06 14:03:33,591 Starting Bokeh server with process id: 5708
2021-12-06 14:03:35,342 WebSocket connection opened
2021-12-06 14:03:35,342 ServerConnection created
2021-12-06 14:03:54,978 WebSocket connection closed: code=1001, reason=None
2021-12-06 14:03:55,250 WebSocket connection opened
2021-12-06 14:03:55,251 ServerConnection created
2021-12-06 14:05:14,467 WebSocket connection closed: code=1001, reason=None
2021-12-06 14:05:14,649 WebSocket connection opened
2021-12-06 14:05:14,650 ServerConnection created
2021-12-06 14:05:25,654 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-06 14:05:25,656 User authentication hooks NOT provided (default user enabled)
2021-12-06 14:05:25,660 Bokeh app running at: http://localhost:8000/prototype
2021-12-06 14:05:25,661 Starting Bokeh server with process id: 5824
2021-12-06 14:05:28,472 WebSocket connection opened
2021-12-06 14:05:28,473 ServerConnection created
2021-12-06 14:09:52,437 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-06 14:09:52,439 User authentication hooks NOT provided (default user enabled)
2021-12-06 14:09:52,444 Bokeh app running at: http://localhost:8000/prototype
2021-12-06 14:09:52,444 Starting Bokeh server with process id: 5976
2021-12-06 14:09:54,931 WebSocket connection opened
2021-12-06 14:09:54,932 ServerConnection created
2021-12-06 14:10:28,119 Failed sending message as connection was closed
2021-12-06 14:10:28,119 Failed sending message as connection was closed
2021-12-06 14:10:28,119 Failed sending message as connection was closed
2021-12-06 14:10:28,119 Failed sending message as connection was closed
2021-12-06 14:10:28,120 Failed sending message as connection was closed
2021-12-06 14:10:28,120 Failed sending message as connection was closed
2021-12-06 14:10:28,121 WebSocket connection closed: code=None, reason=None
2021-12-06 14:10:28,121 WebSocket connection opened
2021-12-06 14:10:28,122 ServerConnection created
2021-12-06 14:11:01,554 WebSocket connection closed: code=1001, reason=None
2021-12-06 14:11:01,722 WebSocket connection opened
2021-12-06 14:11:01,722 ServerConnection created
2021-12-06 14:11:19,690 WebSocket connection closed: code=1001, reason=None
2021-12-06 14:11:19,855 WebSocket connection opened
2021-12-06 14:11:19,855 ServerConnection created
2021-12-06 14:11:27,130 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-06 14:11:27,131 User authentication hooks NOT provided (default user enabled)
2021-12-06 14:11:27,135 Bokeh app running at: http://localhost:8000/prototype
2021-12-06 14:11:27,135 Starting Bokeh server with process id: 6099
2021-12-06 14:11:31,762 WebSocket connection opened
2021-12-06 14:11:31,763 ServerConnection created
2021-12-06 14:11:53,440 WebSocket connection closed: code=1001, reason=None
2021-12-06 14:11:53,636 WebSocket connection opened
2021-12-06 14:11:53,636 ServerConnection created
2021-12-06 14:13:17,480 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-06 14:13:17,481 User authentication hooks NOT provided (default user enabled)
2021-12-06 14:13:17,485 Bokeh app running at: http://localhost:8000/prototype
2021-12-06 14:13:17,485 Starting Bokeh server with process id: 6459
2021-12-06 14:13:19,946 WebSocket connection opened
2021-12-06 14:13:19,947 ServerConnection created
2021-12-06 14:14:39,729 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-06 14:14:39,731 User authentication hooks NOT provided (default user enabled)
2021-12-06 14:14:39,734 Bokeh app running at: http://localhost:8000/prototype
2021-12-06 14:14:39,734 Starting Bokeh server with process id: 6552
2021-12-06 14:14:42,524 WebSocket connection opened
2021-12-06 14:14:42,524 ServerConnection created
2021-12-06 14:15:18,121 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-06 14:15:18,123 User authentication hooks NOT provided (default user enabled)
2021-12-06 14:15:18,127 Bokeh app running at: http://localhost:8000/prototype
2021-12-06 14:15:18,127 Starting Bokeh server with process id: 6624
2021-12-06 14:15:21,575 WebSocket connection opened
2021-12-06 14:15:21,576 ServerConnection created
2021-12-06 14:15:44,900 WebSocket connection closed: code=1001, reason=None
2021-12-06 14:15:45,036 WebSocket connection opened
2021-12-06 14:15:45,036 ServerConnection created
2021-12-06 14:16:14,300 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-06 14:16:14,301 User authentication hooks NOT provided (default user enabled)
2021-12-06 14:16:14,305 Bokeh app running at: http://localhost:8000/prototype
2021-12-06 14:16:14,305 Starting Bokeh server with process id: 6712
2021-12-06 14:16:16,405 WebSocket connection opened
2021-12-06 14:16:16,406 ServerConnection created
2021-12-06 14:16:28,587 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-06 14:16:28,588 User authentication hooks NOT provided (default user enabled)
2021-12-06 14:16:28,594 Bokeh app running at: http://localhost:8000/prototype
2021-12-06 14:16:28,594 Starting Bokeh server with process id: 6785
2021-12-06 14:16:31,105 WebSocket connection opened
2021-12-06 14:16:31,106 ServerConnection created
2021-12-06 14:17:16,272 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-06 14:17:16,273 User authentication hooks NOT provided (default user enabled)
2021-12-06 14:17:16,277 Bokeh app running at: http://localhost:8000/prototype
2021-12-06 14:17:16,277 Starting Bokeh server with process id: 6860
2021-12-06 14:17:18,028 WebSocket connection opened
2021-12-06 14:17:18,028 ServerConnection created
2021-12-06 14:17:30,812 WebSocket connection closed: code=1001, reason=None
2021-12-06 14:17:30,972 WebSocket connection opened
2021-12-06 14:17:30,973 ServerConnection created
2021-12-06 14:18:21,882 WebSocket connection closed: code=1001, reason=None
2021-12-06 14:18:22,088 WebSocket connection opened
2021-12-06 14:18:22,089 ServerConnection created
2021-12-06 14:18:26,797 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-06 14:18:26,799 User authentication hooks NOT provided (default user enabled)
2021-12-06 14:18:26,805 Bokeh app running at: http://localhost:8000/prototype
2021-12-06 14:18:26,805 Starting Bokeh server with process id: 6948
2021-12-06 14:18:28,979 WebSocket connection opened
2021-12-06 14:18:28,981 ServerConnection created
2021-12-06 14:18:57,334 WebSocket connection closed: code=1001, reason=None
2021-12-06 14:18:57,457 WebSocket connection opened
2021-12-06 14:18:57,457 ServerConnection created
2021-12-06 14:19:20,954 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-06 14:19:20,956 User authentication hooks NOT provided (default user enabled)
2021-12-06 14:19:20,960 Bokeh app running at: http://localhost:8000/prototype
2021-12-06 14:19:20,960 Starting Bokeh server with process id: 7029
2021-12-06 14:19:23,190 WebSocket connection opened
2021-12-06 14:19:23,190 ServerConnection created
2021-12-06 14:20:49,419 WebSocket connection closed: code=1001, reason=None
2021-12-06 14:20:49,557 WebSocket connection opened
2021-12-06 14:20:49,558 ServerConnection created
2021-12-06 14:20:56,354 error handling message
 message: Message 'PATCH-DOC' content: {'events': [{'kind': 'MessageSent', 'msg_type': 'bokeh_event', 'msg_data': {'event_name': 'tap', 'event_values': {'sx': 75.953125, 'sy': 88.578125, 'x': 502.83228612879657, 'y': 9530.253729291002}}}], 'references': []} 
 error: ValueError('could not broadcast input array from shape (0,) into shape (1,)')
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/server/protocol_handler.py", line 90, in handle
    work = await handler(message, connection)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/server/session.py", line 67, in _needs_document_lock_wrapper
    result = func(self, *args, **kwargs)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/server/session.py", line 261, in _handle_patch
    message.apply_to_document(self.document, self)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/protocol/messages/patch_doc.py", line 100, in apply_to_document
    doc._with_self_as_curdoc(lambda: doc.apply_json_patch(self.content, setter))
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/document/document.py", line 1198, in _with_self_as_curdoc
    return f()
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/protocol/messages/patch_doc.py", line 100, in <lambda>
    doc._with_self_as_curdoc(lambda: doc.apply_json_patch(self.content, setter))
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/document/document.py", line 398, in apply_json_patch
    self._trigger_on_message(event_json["msg_type"], event_json["msg_data"])
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/document/document.py", line 687, in _trigger_on_message
    cb(msg_data)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/document/document.py", line 356, in apply_json_event
    model._trigger_event(event)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/util/callback_manager.py", line 91, in _trigger_event
    self._document._with_self_as_curdoc(invoke)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/document/document.py", line 1198, in _with_self_as_curdoc
    return f()
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/util/callback_manager.py", line 80, in invoke
    callback(event)
  File "/usr/local/home/kblair/Documents/ETC/prototype/main.py", line 562, in create_data
    etc.set_parameter('wavelengths', [event.x * u.nm])
  File "/usr/local/home/kblair/Documents/ETC/prototype/calculator/ETC.py", line 204, in set_parameter
    self._calculate()
  File "/usr/local/home/kblair/Documents/ETC/prototype/calculator/ETC.py", line 119, in _calculate
    self.exposure[idx, :] = exposure.real.to(u.s)
ValueError: could not broadcast input array from shape (0,) into shape (1,)
2021-12-06 14:20:56,855 error handling message
 message: Message 'PATCH-DOC' content: {'events': [{'kind': 'MessageSent', 'msg_type': 'bokeh_event', 'msg_data': {'event_name': 'tap', 'event_values': {'sx': 152.953125, 'sy': 93.578125, 'x': 628.9701546181375, 'y': 8946.654004229464}}}], 'references': []} 
 error: ValueError('could not broadcast input array from shape (0,) into shape (1,)')
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/server/protocol_handler.py", line 90, in handle
    work = await handler(message, connection)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/server/session.py", line 67, in _needs_document_lock_wrapper
    result = func(self, *args, **kwargs)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/server/session.py", line 261, in _handle_patch
    message.apply_to_document(self.document, self)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/protocol/messages/patch_doc.py", line 100, in apply_to_document
    doc._with_self_as_curdoc(lambda: doc.apply_json_patch(self.content, setter))
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/document/document.py", line 1198, in _with_self_as_curdoc
    return f()
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/protocol/messages/patch_doc.py", line 100, in <lambda>
    doc._with_self_as_curdoc(lambda: doc.apply_json_patch(self.content, setter))
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/document/document.py", line 398, in apply_json_patch
    self._trigger_on_message(event_json["msg_type"], event_json["msg_data"])
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/document/document.py", line 687, in _trigger_on_message
    cb(msg_data)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/document/document.py", line 356, in apply_json_event
    model._trigger_event(event)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/util/callback_manager.py", line 91, in _trigger_event
    self._document._with_self_as_curdoc(invoke)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/document/document.py", line 1198, in _with_self_as_curdoc
    return f()
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/util/callback_manager.py", line 80, in invoke
    callback(event)
  File "/usr/local/home/kblair/Documents/ETC/prototype/main.py", line 562, in create_data
    etc.set_parameter('wavelengths', [event.x * u.nm])
  File "/usr/local/home/kblair/Documents/ETC/prototype/calculator/ETC.py", line 204, in set_parameter
    self._calculate()
  File "/usr/local/home/kblair/Documents/ETC/prototype/calculator/ETC.py", line 119, in _calculate
    self.exposure[idx, :] = exposure.real.to(u.s)
ValueError: could not broadcast input array from shape (0,) into shape (1,)
2021-12-06 14:20:59,381 error handling message
 message: Message 'PATCH-DOC' content: {'events': [{'kind': 'MessageSent', 'msg_type': 'bokeh_event', 'msg_data': {'event_name': 'tap', 'event_values': {'sx': 108.953125, 'sy': 126.578125, 'x': 556.8913726242284, 'y': 5094.895818823312}}}], 'references': []} 
 error: ValueError('could not broadcast input array from shape (0,) into shape (1,)')
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/server/protocol_handler.py", line 90, in handle
    work = await handler(message, connection)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/server/session.py", line 67, in _needs_document_lock_wrapper
    result = func(self, *args, **kwargs)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/server/session.py", line 261, in _handle_patch
    message.apply_to_document(self.document, self)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/protocol/messages/patch_doc.py", line 100, in apply_to_document
    doc._with_self_as_curdoc(lambda: doc.apply_json_patch(self.content, setter))
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/document/document.py", line 1198, in _with_self_as_curdoc
    return f()
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/protocol/messages/patch_doc.py", line 100, in <lambda>
    doc._with_self_as_curdoc(lambda: doc.apply_json_patch(self.content, setter))
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/document/document.py", line 398, in apply_json_patch
    self._trigger_on_message(event_json["msg_type"], event_json["msg_data"])
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/document/document.py", line 687, in _trigger_on_message
    cb(msg_data)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/document/document.py", line 356, in apply_json_event
    model._trigger_event(event)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/util/callback_manager.py", line 91, in _trigger_event
    self._document._with_self_as_curdoc(invoke)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/document/document.py", line 1198, in _with_self_as_curdoc
    return f()
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/util/callback_manager.py", line 80, in invoke
    callback(event)
  File "/usr/local/home/kblair/Documents/ETC/prototype/main.py", line 562, in create_data
    etc.set_parameter('wavelengths', [event.x * u.nm])
  File "/usr/local/home/kblair/Documents/ETC/prototype/calculator/ETC.py", line 204, in set_parameter
    self._calculate()
  File "/usr/local/home/kblair/Documents/ETC/prototype/calculator/ETC.py", line 119, in _calculate
    self.exposure[idx, :] = exposure.real.to(u.s)
ValueError: could not broadcast input array from shape (0,) into shape (1,)
2021-12-06 14:21:02,387 error handling message
 message: Message 'PATCH-DOC' content: {'events': [{'kind': 'ModelChanged', 'model': {'id': '44039'}, 'attr': 'value', 'new': 'signal to noise ratio'}], 'references': []} 
 error: IndexError('boolean index did not match indexed array along dimension 0; dimension is 0 but corresponding boolean dimension is 1')
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/server/protocol_handler.py", line 90, in handle
    work = await handler(message, connection)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/server/session.py", line 67, in _needs_document_lock_wrapper
    result = func(self, *args, **kwargs)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/server/session.py", line 261, in _handle_patch
    message.apply_to_document(self.document, self)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/protocol/messages/patch_doc.py", line 100, in apply_to_document
    doc._with_self_as_curdoc(lambda: doc.apply_json_patch(self.content, setter))
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/document/document.py", line 1198, in _with_self_as_curdoc
    return f()
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/protocol/messages/patch_doc.py", line 100, in <lambda>
    doc._with_self_as_curdoc(lambda: doc.apply_json_patch(self.content, setter))
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/document/document.py", line 411, in apply_json_patch
    patched_obj.set_from_json(attr, value, models=references, setter=setter)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/core/has_props.py", line 412, in set_from_json
    descriptor.set_from_json(self, json, models, setter)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/core/property/descriptors.py", line 623, in set_from_json
    return super().set_from_json(obj, self.property.from_json(json, models), models, setter)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/core/property/descriptors.py", line 327, in set_from_json
    self._internal_set(obj, json, setter=setter)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/core/property/descriptors.py", line 786, in _internal_set
    self._real_set(obj, old, value, hint=hint, setter=setter)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/core/property/descriptors.py", line 849, in _real_set
    self._trigger(obj, old, value, hint=hint, setter=setter)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/core/property/descriptors.py", line 926, in _trigger
    obj.trigger(self.name, old, value, hint, setter)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/model.py", line 682, in trigger
    super().trigger(descriptor.name, old, new, hint=hint, setter=setter)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/util/callback_manager.py", line 163, in trigger
    self._document._notify_change(self, attr, old, new, hint, setter, invoke)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/document/document.py", line 1090, in _notify_change
    self._trigger_on_change(event)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/document/document.py", line 1180, in _trigger_on_change
    self._with_self_as_curdoc(event.callback_invoker)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/document/document.py", line 1198, in _with_self_as_curdoc
    return f()
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/util/callback_manager.py", line 161, in invoke
    callback(attr, old, new)
  File "/usr/local/home/kblair/Documents/ETC/prototype/main.py", line 215, in target_callback
    update_results()
  File "/usr/local/home/kblair/Documents/ETC/prototype/main.py", line 63, in update_results
    summary.load()
  File "/usr/local/home/kblair/Documents/ETC/prototype/main.py", line 459, in load
    f'{etc.source_flux[wavelength_index][0].to("erg / (cm^2 s Angstrom)", equivalencies=u.spectral_density(central_wavelength)).value:.1} flam',
  File "/usr/local/anaconda3/lib/python3.8/site-packages/astropy/units/quantity.py", line 1045, in __getitem__
    out = super().__getitem__(key)
IndexError: boolean index did not match indexed array along dimension 0; dimension is 0 but corresponding boolean dimension is 1
2021-12-06 14:21:06,334 error handling message
 message: Message 'PATCH-DOC' content: {'events': [{'kind': 'ModelChanged', 'model': {'id': '44039'}, 'attr': 'value', 'new': 'exposure'}], 'references': []} 
 error: ValueError('could not broadcast input array from shape (0,) into shape (1,)')
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/server/protocol_handler.py", line 90, in handle
    work = await handler(message, connection)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/server/session.py", line 67, in _needs_document_lock_wrapper
    result = func(self, *args, **kwargs)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/server/session.py", line 261, in _handle_patch
    message.apply_to_document(self.document, self)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/protocol/messages/patch_doc.py", line 100, in apply_to_document
    doc._with_self_as_curdoc(lambda: doc.apply_json_patch(self.content, setter))
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/document/document.py", line 1198, in _with_self_as_curdoc
    return f()
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/protocol/messages/patch_doc.py", line 100, in <lambda>
    doc._with_self_as_curdoc(lambda: doc.apply_json_patch(self.content, setter))
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/document/document.py", line 411, in apply_json_patch
    patched_obj.set_from_json(attr, value, models=references, setter=setter)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/core/has_props.py", line 412, in set_from_json
    descriptor.set_from_json(self, json, models, setter)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/core/property/descriptors.py", line 623, in set_from_json
    return super().set_from_json(obj, self.property.from_json(json, models), models, setter)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/core/property/descriptors.py", line 327, in set_from_json
    self._internal_set(obj, json, setter=setter)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/core/property/descriptors.py", line 786, in _internal_set
    self._real_set(obj, old, value, hint=hint, setter=setter)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/core/property/descriptors.py", line 849, in _real_set
    self._trigger(obj, old, value, hint=hint, setter=setter)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/core/property/descriptors.py", line 926, in _trigger
    obj.trigger(self.name, old, value, hint, setter)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/model.py", line 682, in trigger
    super().trigger(descriptor.name, old, new, hint=hint, setter=setter)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/util/callback_manager.py", line 163, in trigger
    self._document._notify_change(self, attr, old, new, hint, setter, invoke)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/document/document.py", line 1090, in _notify_change
    self._trigger_on_change(event)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/document/document.py", line 1180, in _trigger_on_change
    self._with_self_as_curdoc(event.callback_invoker)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/document/document.py", line 1198, in _with_self_as_curdoc
    return f()
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bokeh/util/callback_manager.py", line 161, in invoke
    callback(attr, old, new)
  File "/usr/local/home/kblair/Documents/ETC/prototype/main.py", line 201, in target_callback
    etc.set_parameter('signal_noise_ratio', etc.config.defaults.signal_noise_ratio)
  File "/usr/local/home/kblair/Documents/ETC/prototype/calculator/ETC.py", line 204, in set_parameter
    self._calculate()
  File "/usr/local/home/kblair/Documents/ETC/prototype/calculator/ETC.py", line 119, in _calculate
    self.exposure[idx, :] = exposure.real.to(u.s)
ValueError: could not broadcast input array from shape (0,) into shape (1,)
2021-12-08 09:31:58,449 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-08 09:31:58,451 User authentication hooks NOT provided (default user enabled)
2021-12-08 09:31:58,456 Bokeh app running at: http://localhost:8000/prototype
2021-12-08 09:31:58,456 Starting Bokeh server with process id: 24721
2021-12-08 09:32:02,468 WebSocket connection opened
2021-12-08 09:32:02,469 ServerConnection created
2021-12-08 09:38:40,575 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-08 09:38:40,576 User authentication hooks NOT provided (default user enabled)
2021-12-08 09:38:40,579 Bokeh app running at: http://localhost:8000/prototype
2021-12-08 09:38:40,580 Starting Bokeh server with process id: 24981
2021-12-08 09:40:01,771 WebSocket connection opened
2021-12-08 09:40:01,772 ServerConnection created
2021-12-08 11:12:18,512 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-08 11:12:18,513 User authentication hooks NOT provided (default user enabled)
2021-12-08 11:12:18,517 Bokeh app running at: http://localhost:8000/prototype
2021-12-08 11:12:18,517 Starting Bokeh server with process id: 28143
2021-12-08 11:12:21,490 WebSocket connection opened
2021-12-08 11:12:21,490 ServerConnection created
2021-12-08 11:12:46,859 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-08 11:12:46,861 User authentication hooks NOT provided (default user enabled)
2021-12-08 11:12:46,864 Bokeh app running at: http://localhost:8000/prototype
2021-12-08 11:12:46,865 Starting Bokeh server with process id: 28218
2021-12-08 11:12:49,937 WebSocket connection opened
2021-12-08 11:12:49,937 ServerConnection created
2021-12-08 11:14:34,051 WebSocket connection closed: code=1001, reason=None
2021-12-08 11:14:34,275 WebSocket connection opened
2021-12-08 11:14:34,276 ServerConnection created
2021-12-08 11:17:48,659 WebSocket connection closed: code=1001, reason=None
2021-12-08 11:17:48,884 WebSocket connection opened
2021-12-08 11:17:48,885 ServerConnection created
2021-12-08 11:23:37,570 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-08 11:23:37,572 User authentication hooks NOT provided (default user enabled)
2021-12-08 11:23:37,575 Bokeh app running at: http://localhost:8000/prototype
2021-12-08 11:23:37,575 Starting Bokeh server with process id: 28507
2021-12-08 11:23:39,234 WebSocket connection opened
2021-12-08 11:23:39,234 ServerConnection created
2021-12-08 11:24:01,851 WebSocket connection closed: code=1001, reason=None
2021-12-08 11:24:02,055 WebSocket connection opened
2021-12-08 11:24:02,056 ServerConnection created
2021-12-08 11:24:05,362 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-08 11:24:05,363 User authentication hooks NOT provided (default user enabled)
2021-12-08 11:24:05,367 Bokeh app running at: http://localhost:8000/prototype
2021-12-08 11:24:05,367 Starting Bokeh server with process id: 28581
2021-12-08 11:24:06,980 WebSocket connection opened
2021-12-08 11:24:06,981 ServerConnection created
2021-12-08 11:24:30,222 WebSocket connection closed: code=1001, reason=None
2021-12-08 11:24:30,414 WebSocket connection opened
2021-12-08 11:24:30,415 ServerConnection created
2021-12-08 11:24:52,053 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-08 11:24:52,054 User authentication hooks NOT provided (default user enabled)
2021-12-08 11:24:52,058 Bokeh app running at: http://localhost:8000/prototype
2021-12-08 11:24:52,058 Starting Bokeh server with process id: 28656
2021-12-08 11:24:56,602 WebSocket connection opened
2021-12-08 11:24:56,602 ServerConnection created
2021-12-08 11:25:11,350 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-08 11:25:11,351 User authentication hooks NOT provided (default user enabled)
2021-12-08 11:25:11,355 Bokeh app running at: http://localhost:8000/prototype
2021-12-08 11:25:11,355 Starting Bokeh server with process id: 28720
2021-12-08 11:25:13,199 WebSocket connection opened
2021-12-08 11:25:13,199 ServerConnection created
2021-12-08 11:25:21,521 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-08 11:25:21,523 User authentication hooks NOT provided (default user enabled)
2021-12-08 11:25:21,526 Bokeh app running at: http://localhost:8000/prototype
2021-12-08 11:25:21,526 Starting Bokeh server with process id: 28775
2021-12-08 11:25:23,905 WebSocket connection opened
2021-12-08 11:25:23,905 ServerConnection created
2021-12-08 11:25:33,696 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-08 11:25:33,698 User authentication hooks NOT provided (default user enabled)
2021-12-08 11:25:33,702 Bokeh app running at: http://localhost:8000/prototype
2021-12-08 11:25:33,702 Starting Bokeh server with process id: 28846
2021-12-08 11:25:35,917 WebSocket connection opened
2021-12-08 11:25:35,917 ServerConnection created
2021-12-08 11:26:30,983 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-08 11:26:30,985 User authentication hooks NOT provided (default user enabled)
2021-12-08 11:26:30,988 Bokeh app running at: http://localhost:8000/prototype
2021-12-08 11:26:30,988 Starting Bokeh server with process id: 28930
2021-12-08 11:26:32,581 WebSocket connection opened
2021-12-08 11:26:32,582 ServerConnection created
2021-12-08 11:27:00,838 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-08 11:27:00,839 User authentication hooks NOT provided (default user enabled)
2021-12-08 11:27:00,843 Bokeh app running at: http://localhost:8000/prototype
2021-12-08 11:27:00,844 Starting Bokeh server with process id: 28987
2021-12-08 11:27:02,717 WebSocket connection opened
2021-12-08 11:27:02,718 ServerConnection created
2021-12-08 11:27:34,922 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-08 11:27:34,923 User authentication hooks NOT provided (default user enabled)
2021-12-08 11:27:34,927 Bokeh app running at: http://localhost:8000/prototype
2021-12-08 11:27:34,927 Starting Bokeh server with process id: 29059
2021-12-08 11:27:36,617 WebSocket connection opened
2021-12-08 11:27:36,617 ServerConnection created
2021-12-08 11:27:52,159 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-08 11:27:52,160 User authentication hooks NOT provided (default user enabled)
2021-12-08 11:27:52,164 Bokeh app running at: http://localhost:8000/prototype
2021-12-08 11:27:52,164 Starting Bokeh server with process id: 29117
2021-12-08 11:27:54,165 WebSocket connection opened
2021-12-08 11:27:54,166 ServerConnection created
2021-12-08 11:28:12,926 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-08 11:28:12,928 User authentication hooks NOT provided (default user enabled)
2021-12-08 11:28:12,932 Bokeh app running at: http://localhost:8000/prototype
2021-12-08 11:28:12,932 Starting Bokeh server with process id: 29182
2021-12-08 11:28:15,176 WebSocket connection opened
2021-12-08 11:28:15,177 ServerConnection created
2021-12-08 11:30:19,058 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-08 11:30:19,059 User authentication hooks NOT provided (default user enabled)
2021-12-08 11:30:19,063 Bokeh app running at: http://localhost:8000/prototype
2021-12-08 11:30:19,063 Starting Bokeh server with process id: 29292
2021-12-08 11:30:20,793 WebSocket connection opened
2021-12-08 11:30:20,793 ServerConnection created
2021-12-08 11:31:03,196 WebSocket connection closed: code=1001, reason=None
2021-12-08 11:31:03,293 WebSocket connection opened
2021-12-08 11:31:03,294 ServerConnection created
2021-12-08 11:31:25,730 WebSocket connection closed: code=1001, reason=None
2021-12-08 11:31:25,829 WebSocket connection opened
2021-12-08 11:31:25,829 ServerConnection created
2021-12-08 11:31:34,488 WebSocket connection opened
2021-12-08 11:31:34,489 Failed sending message as connection was closed
2021-12-08 11:31:34,489 Failed sending message as connection was closed
2021-12-08 11:31:34,489 Failed sending message as connection was closed
2021-12-08 11:31:34,489 Failed sending message as connection was closed
2021-12-08 11:31:34,489 Failed sending message as connection was closed
2021-12-08 11:31:34,490 Failed sending message as connection was closed
2021-12-08 11:31:34,490 Failed sending message as connection was closed
2021-12-08 11:31:34,490 Failed sending message as connection was closed
2021-12-08 11:31:34,490 Failed sending message as connection was closed
2021-12-08 11:31:34,490 Failed sending message as connection was closed
2021-12-08 11:31:34,490 Failed sending message as connection was closed
2021-12-08 11:31:34,490 Failed sending message as connection was closed
2021-12-08 11:31:34,491 Failed sending message as connection was closed
2021-12-08 11:31:34,491 Failed sending message as connection was closed
2021-12-08 11:31:34,491 Failed sending message as connection was closed
2021-12-08 11:31:34,491 Failed sending message as connection was closed
2021-12-08 11:31:34,491 Failed sending message as connection was closed
2021-12-08 11:31:34,491 Failed sending message as connection was closed
2021-12-08 11:31:34,491 Failed sending message as connection was closed
2021-12-08 11:31:34,492 Failed sending message as connection was closed
2021-12-08 11:31:34,492 Failed sending message as connection was closed
2021-12-08 11:31:34,492 Failed sending message as connection was closed
2021-12-08 11:31:34,492 Failed sending message as connection was closed
2021-12-08 11:31:34,492 Failed sending message as connection was closed
2021-12-08 11:31:34,492 Failed sending message as connection was closed
2021-12-08 11:31:34,492 Failed sending message as connection was closed
2021-12-08 11:31:34,492 Failed sending message as connection was closed
2021-12-08 11:31:34,493 WebSocket connection closed: code=None, reason=None
2021-12-08 11:31:34,493 ServerConnection created
2021-12-08 11:33:24,856 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-08 11:33:24,858 User authentication hooks NOT provided (default user enabled)
2021-12-08 11:33:24,862 Bokeh app running at: http://localhost:8000/prototype
2021-12-08 11:33:24,862 Starting Bokeh server with process id: 29405
2021-12-08 11:33:26,620 WebSocket connection opened
2021-12-08 11:33:26,621 ServerConnection created
2021-12-08 11:36:51,360 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-12-08 11:36:51,361 User authentication hooks NOT provided (default user enabled)
2021-12-08 11:36:51,365 Bokeh app running at: http://localhost:8000/prototype
2021-12-08 11:36:51,365 Starting Bokeh server with process id: 29614
2021-12-08 11:36:53,750 WebSocket connection opened
2021-12-08 11:36:53,751 ServerConnection created
